//! Material 3 editor workspace with one deterministic spatial hierarchy.

use bevy::ecs::system::{ParamSet,SystemParam};
use bevy::prelude::*;
use bevy_egui::{egui,EguiContexts};

use crate::{assets::AssetDatabase,command::{EditorCommandBus,EditorCommandRegistry},docking::{DockViewer,EditorDockState,TransformEdit},editor::{EditorPluginRegistry,EditorUiState,ViewportMode},history::TransformHistory,profiler::EditorProfiler,project::EditorMode,project::ProjectState,scene_model::EditorParent,selection::SelectionState,settings::EditorSettingsState,viewport::EditorEntity};

pub mod actions; pub mod assets; pub mod design_system; pub mod layout; pub mod persistence; pub mod settings; pub mod theme; pub mod welcome; pub mod workspace;
use actions::{apply_entity_actions,UiActions};
use design_system::{material_surface,toolbar_icon,toolbar_text_button};
use layout::{BottomPage,LeftPanelPage,LayoutState,MainPage,SceneMode,ToolMode};
use persistence::save_editor_project;
use welcome::{show_welcome,WelcomeState};

#[derive(Resource,Debug,Clone)]
pub struct WorkspaceUiState{pub layout:LayoutState,pub hierarchy_filter:String,pub asset_filter:String,pub search_query:String,pub toast:Option<String>,pub toast_seconds:f32}
impl Default for WorkspaceUiState{fn default()->Self{Self{layout:LayoutState::default(),hierarchy_filter:String::new(),asset_filter:String::new(),search_query:String::new(),toast:None,toast_seconds:0.0}}}
impl WorkspaceUiState{pub fn toast(&mut self,text:impl Into<String>){self.toast=Some(text.into());self.toast_seconds=3.0;}pub fn tick(&mut self,seconds:f32){if self.toast_seconds>0.0{self.toast_seconds=(self.toast_seconds-seconds).max(0.0);if self.toast_seconds==0.0{self.toast=None;}}}}

#[derive(SystemParam)]
pub struct EditorUiParams<'w,'s>{pub contexts:EguiContexts<'w,'s>,pub workspace:ResMut<'w,WorkspaceUiState>,pub dock:ResMut<'w,EditorDockState>,pub state:ResMut<'w,EditorUiState>,pub settings:ResMut<'w,EditorSettingsState>,pub welcome:ResMut<'w,WelcomeState>,pub project:ResMut<'w,ProjectState>,pub selection:ResMut<'w,SelectionState>,pub registry:Res<'w,EditorCommandRegistry>,pub command_bus:ResMut<'w,EditorCommandBus>,pub plugins:Res<'w,EditorPluginRegistry>,pub assets:ResMut<'w,AssetDatabase>,pub profiler:Res<'w,EditorProfiler>,pub history:ResMut<'w,TransformHistory>,pub transforms:Query<'w,'s,&'static Transform,With<EditorEntity>>,pub names:Query<'w,'s,(Entity,Option<&'static Name>),With<EditorEntity>>,pub visibility:Query<'w,'s,&'static Visibility,With<EditorEntity>>,pub parents:ParamSet<'w,'s,(Query<'w,'s,Option<&'static EditorParent>,With<EditorEntity>>,Query<'w,'s,&'static mut EditorParent,With<EditorEntity>>)>,pub commands:Commands<'w,'s>}

pub fn install_editor_ui(app:&mut App){app.init_resource::<WelcomeState>().init_resource::<WorkspaceUiState>().add_systems(bevy_egui::EguiPrimaryContextPass,editor_ui_system).add_systems(Update,ui_tick_system);}
fn ui_tick_system(time:Res<Time>,mut workspace:ResMut<WorkspaceUiState>){workspace.tick(time.delta_secs());}

fn editor_ui_system(mut p:EditorUiParams)->Result{let ctx=p.contexts.ctx_mut()?;theme::apply_material_theme(ctx);theme::apply_material_settings(ctx,&p.settings.settings);if p.welcome.visible{return draw_welcome(ctx,&mut p);}
let entities=snapshot_entities(&p.names,&p.workspace.hierarchy_filter);let parents=snapshot_parents(&p,&entities);let selected_transform=snapshot_transform(&p);let selected_name=snapshot_name(&p);let selected_visible=snapshot_visible(&p);let assets=snapshot_assets(&p,&p.workspace.asset_filter);let plugins=snapshot_plugins(&p);let project_name=p.project.name.clone();let dirty=p.project.dirty;let mode=p.project.mode;let status=p.state.status.clone();let accent=egui::Color32::from_rgb(p.settings.settings.appearance.accent[0],p.settings.settings.appearance.accent[1],p.settings.settings.appearance.accent[2]);let bottom_page=p.workspace.layout.bottom_page;
let mut actions=UiActions::default();
egui::TopBottomPanel::top("editor_top").exact_height(layout::APP_BAR_HEIGHT).show_separator_line(false).show(ctx,|ui|draw_app_bar(ui,&project_name,dirty,mode,&status,accent,&mut p));
egui::SidePanel::left("editor_nav").exact_width(layout::NAV_RAIL_WIDTH).resizable(false).show_separator_line(false).show(ctx,|ui|draw_navigation(ui,&mut p));
if p.workspace.layout.bottom_open{egui::TopBottomPanel::bottom("editor_bottom").exact_height(layout::BOTTOM_PANEL_HEIGHT).show_separator_line(false).show(ctx,|ui|draw_bottom_panel(ui,&mut p,bottom_page));}
if p.workspace.layout.left_open{egui::SidePanel::left("editor_left").default_width(layout::LEFT_PANEL_WIDTH).min_width(220.0).max_width(420.0).show_separator_line(false).show(ctx,|ui|draw_left_workspace(ui,&mut p,&entities,&parents,&assets));}
if p.workspace.layout.right_open{egui::SidePanel::right("editor_right").default_width(layout::RIGHT_PANEL_WIDTH).min_width(260.0).max_width(500.0).show_separator_line(false).show(ctx,|ui|{let mut viewer=make_viewer(&mut p,&entities,&parents,selected_transform,selected_name,selected_visible,&plugins);viewer.show_inspector(ui);actions=UiActions::from(&viewer);});}
egui::CentralPanel::default().show(ctx,|ui|draw_scene_workspace(ui,&mut p,&entities,&parents,accent));
if let Some(message)=&p.workspace.toast{egui::Area::new("editor_toast".into()).anchor(egui::Align2::CENTER_BOTTOM,[0.0,-24.0]).show(ctx,|ui|{design_system::overlay(ui,|ui|ui.label(message));});}
apply_actions(&mut p,&actions);Ok(())}

fn draw_welcome(ctx:&egui::Context,p:&mut EditorUiParams)->Result{let mut ui=egui::Ui::new(ctx.clone(),"welcome".into(),egui::UiBuilder::new().max_rect(ctx.screen_rect()));show_welcome(&mut ui,&mut p.welcome,&mut p.project,&mut p.state);Ok(())}
fn snapshot_entities(q:&Query<(Entity,Option<&Name>),With<EditorEntity>>,filter:&str)->Vec<(Entity,String)>{let f=filter.to_ascii_lowercase();q.iter().filter_map(|(e,n)|{let value=n.map(|x|x.as_str().to_owned()).unwrap_or_else(||format!("Entity {:?}",e));if f.is_empty()||value.to_ascii_lowercase().contains(&f){Some((e,value))}else{None}}).collect()}
fn snapshot_parents(p:&EditorUiParams,entities:&[(Entity,String)])->Vec<(Entity,Option<Entity>)>{let q=p.parents.p0();entities.iter().map(|(e,_)|(*e,q.get(*e).ok().flatten().and_then(|x|x.0))).collect()}
fn snapshot_transform(p:&EditorUiParams)->Option<TransformEdit>{p.selection.primary().and_then(|e|p.transforms.get(e).ok()).map(|t|{let(x,y,z)=t.rotation.to_euler(EulerRot::XYZ);TransformEdit{entity:p.selection.primary().unwrap(),translation:t.translation,rotation:Vec3::new(x.to_degrees(),y.to_degrees(),z.to_degrees()),scale:t.scale}})}
fn snapshot_name(p:&EditorUiParams)->Option<String>{p.selection.primary().and_then(|e|p.names.get(e).ok()).and_then(|(_,n)|n.map(|x|x.as_str().to_owned()))}
fn snapshot_visible(p:&EditorUiParams)->Option<bool>{p.selection.primary().and_then(|e|p.visibility.get(e).ok()).map(|v|!matches!(v,Visibility::Hidden))}
fn snapshot_assets(p:&EditorUiParams,filter:&str)->Vec<String>{let f=filter.to_ascii_lowercase();p.assets.entries.iter().filter_map(|e|{let v=e.path.display().to_string();if f.is_empty()||v.to_ascii_lowercase().contains(&f){Some(v)}else{None}}).take(3000).collect()}
fn snapshot_plugins(p:&EditorUiParams)->Vec<String>{p.plugins.iter().map(|(n,v)|format!("{n} v{v}")).collect()}
fn make_viewer<'a>(p:&'a mut EditorUiParams,entities:&'a[(Entity,String)],parents:&'a[(Entity,Option<Entity>)],selected_transform:Option<TransformEdit>,selected_name:Option<String>,selected_visible:Option<bool>,plugins:&'a[String])->DockViewer<'a>{DockViewer{project:&mut p.project,selection:&mut p.selection,ui_state:&mut p.state,settings:&mut p.settings,profiler:&p.profiler,assets:&mut p.assets,entities,parents,selected_transform,selected_name,selected_visible,plugin_names:plugins,command_count:p.registry.iter().count(),transform_edit:None,name_edit:None,visibility_edit:None,viewport_focused:false,create_entity:false,delete_entity:None,duplicate_entity:None,save_requested:false,parent_selected:false,unparent_selected:false}}
fn apply_actions(p:&mut EditorUiParams,a:&UiActions){let mut parents=p.parents.p1();apply_entity_actions(a,&mut p.commands,&mut p.selection,&mut p.project,&mut p.history,&p.transforms,&mut parents);drop(parents);if a.save_requested{let parents=p.parents.p0();let scene=p.names.iter().filter_map(|(e,n)|{let name=n.map(|x|x.as_str().to_owned()).unwrap_or_else(||format!("Entity {:?}",e));let transform=p.transforms.get(e).ok().copied()?;let parent=parents.get(e).ok().flatten().and_then(|x|x.0);Some((e,name,transform,parent))}).collect::<Vec<_>>();save_editor_project(&mut p.project,&mut p.state,&scene);p.workspace.toast("Scene saved");}}

fn draw_app_bar(ui:&mut egui::Ui,project:&str,dirty:bool,mode:EditorMode,status:&str,accent:egui::Color32,p:&mut EditorUiParams){design_system::toolbar(ui,|ui|{ui.horizontal(|ui|{ui.label(egui::RichText::new("✦").size(19.0).color(accent));ui.label(egui::RichText::new("Bevy-GUI").strong());ui.label("/");ui.label(project);design_system::dirty_badge(ui,dirty);ui.separator();if toolbar_text_button(ui,"Save").clicked(){p.command_bus.emit(crate::EditorCommandId("project.save"));}if toolbar_text_button(ui,"Build").clicked(){p.command_bus.emit(crate::EditorCommandId("project.export"));}if toolbar_text_button(ui,"Assets").clicked(){p.command_bus.emit(crate::EditorCommandId("assets.refresh"));}ui.separator();if toolbar_icon(ui,"▶","Play").clicked(){p.command_bus.emit(crate::EditorCommandId("project.play"));}if toolbar_icon(ui,"Ⅱ","Pause").clicked(){p.command_bus.emit(crate::EditorCommandId("project.pause"));}if toolbar_icon(ui,"■","Stop").clicked(){p.command_bus.emit(crate::EditorCommandId("project.stop"));}ui.with_layout(egui::Layout::right_to_left(egui::Align::Center),|ui|{let e=match mode{EditorMode::Edit=>design_system::Emphasis::Info,EditorMode::Play=>design_system::Emphasis::Success,EditorMode::Paused=>design_system::Emphasis::Warning};design_system::status(ui,status,e);});});});}

fn draw_navigation(ui:&mut egui::Ui,p:&mut EditorUiParams){design_system::material_surface(ui,|ui|{ui.vertical_centered(|ui|{ui.label(egui::RichText::new("✦").size(23.0));ui.add_space(12.0);nav_item(ui,"⌂","Home",MainPage::Home,p);nav_item(ui,"▣","Scene",MainPage::Scene,p);nav_item(ui,"◫","Assets",MainPage::Assets,p);nav_item(ui,"⚙","Settings",MainPage::Settings,p);ui.add_space(ui.available_height().max(0.0));if design_system::nav_button(ui,"▤","Console",p.workspace.layout.bottom_open){p.workspace.layout.toggle_bottom(BottomPage::Console);}if design_system::nav_button(ui,"◌","Profiler",p.workspace.layout.bottom_open&&p.workspace.layout.bottom_page==BottomPage::Profiler){p.workspace.layout.toggle_bottom(BottomPage::Profiler);}});});}
fn nav_item(ui:&mut egui::Ui,icon:&str,label:&str,page:MainPage,p:&mut EditorUiParams){if design_system::nav_button(ui,icon,label,p.workspace.layout.page==page).clicked(){p.workspace.layout.set_page(page);}}

fn draw_left_workspace(ui:&mut egui::Ui,p:&mut EditorUiParams,entities:&[(Entity,String)],parents:&[(Entity,Option<Entity>)],assets:&[String]){design_system::card(ui,design_system::Surface::Container,|ui|{ui.horizontal(|ui|{if ui.selectable_label(p.workspace.layout.left_page==LeftPanelPage::Hierarchy,"Hierarchy").clicked(){p.workspace.layout.left_page=LeftPanelPage::Hierarchy;}if ui.selectable_label(p.workspace.layout.left_page==LeftPanelPage::Assets,"Assets").clicked(){p.workspace.layout.left_page=LeftPanelPage::Assets;}});design_system::separator(ui);match p.workspace.layout.left_page{LeftPanelPage::Hierarchy=>draw_hierarchy(ui,p,entities,parents),LeftPanelPage::Assets=>draw_assets(ui,p,assets)}})}
fn draw_hierarchy(ui:&mut egui::Ui,p:&mut EditorUiParams,entities:&[(Entity,String)],parents:&[(Entity,Option<Entity>)]){design_system::heading_row(ui,"Scene",Some(entities.len()));design_system::search(ui,&mut p.workspace.hierarchy_filter,"Filter entities");ui.horizontal(|ui|{if design_system::create(ui){p.command_bus.emit(crate::EditorCommandId("scene.new_entity"));}if design_system::duplicate(ui){p.command_bus.emit(crate::EditorCommandId("scene.duplicate"));}if design_system::remove(ui){p.command_bus.emit(crate::EditorCommandId("scene.delete"));}});design_system::separator(ui);for(e,name)in entities{let depth=depth_of(*e,parents);if design_system::tree_row(ui,depth,"◈",name,p.selection.contains(*e)).clicked(){p.selection.select(*e);}}}
fn draw_assets(ui:&mut egui::Ui,p:&mut EditorUiParams,assets:&[String]){design_system::heading_row(ui,"Assets",Some(assets.len()));design_system::search(ui,&mut p.workspace.asset_filter,"Search assets");if design_system::refresh(ui){p.command_bus.emit(crate::EditorCommandId("assets.refresh"));}design_system::separator(ui);for(path)in assets{let _=ui.selectable_label(false,path);}}
fn depth_of(entity:Entity,parents:&[(Entity,Option<Entity>)])->usize{let mut d=0;let mut current=entity;for _ in 0..64{let parent=parents.iter().find(|(e,_)|*e==current).and_then(|(_,p)|*p);match parent{Some(v)=>{d+=1;current=v;},None=>break}}d.min(12)}

fn draw_scene_workspace(ui:&mut egui::Ui,p:&mut EditorUiParams,entities:&[(Entity,String)],parents:&[(Entity,Option<Entity>)],accent:egui::Color32){design_system::material_surface(ui,|ui|{design_system::toolbar(ui,|ui|{ui.horizontal(|ui|{if design_system::scene_mode_2d(ui,p.workspace.layout.scene_mode==SceneMode::TwoD){p.workspace.layout.scene_mode=SceneMode::TwoD;p.state.viewport_mode=ViewportMode::TwoD;}if design_system::scene_mode(ui,p.workspace.layout.scene_mode==SceneMode::ThreeD){p.workspace.layout.scene_mode=SceneMode::ThreeD;p.state.viewport_mode=ViewportMode::ThreeD;}ui.separator();let tool=match p.workspace.layout.tool{ToolMode::Select=>design_system::tool_select(ui,true),ToolMode::Move=>design_system::tool_move(ui,true),ToolMode::Rotate=>design_system::tool_rotate(ui,true),ToolMode::Scale=>design_system::tool_scale(ui,true),ToolMode::Pan=>design_system::tool_select(ui,true)};let _=tool;if design_system::tool_snap(ui,p.workspace.layout.snap){p.workspace.layout.snap=!p.workspace.layout.snap;}if design_system::tool_space(ui,p.workspace.layout.world_space){p.workspace.layout.world_space=!p.workspace.layout.world_space;}ui.with_layout(egui::Layout::right_to_left(egui::Align::Center),|ui|design_system::badge(ui,&format!("{} selected",p.selection.entities.len()),design_system::Emphasis::Primary));});});design_system::separator(ui);egui::Frame::new().fill(egui::Color32::from_rgb(9,10,13)).corner_radius(egui::CornerRadius::same(12)).show(ui,|ui|{ui.set_min_height(ui.available_height().max(320.0));ui.centered_and_justified(|ui|{ui.vertical_centered(|ui|{ui.label(egui::RichText::new(if p.workspace.layout.scene_mode==SceneMode::TwoD{"2D Scene"}else{"3D Scene"}).size(24.0).strong());ui.label(if p.workspace.layout.scene_mode==SceneMode::TwoD{"Orthographic editor · grid · pan · zoom"}else{"Free camera · picking · transform gizmo"});ui.add_space(10.0);ui.label(format!("{} entities",entities.len()));if let Some(selected)=p.selection.primary(){ui.label(format!("Selected {:?}",selected));}if !parents.is_empty(){ui.label(format!("{} parent relations",parents.iter().filter(|(_,p)|p.is_some()).count()));}ui.add_space(8.0);if ui.button("Focus Viewport").clicked(){p.state.status="Viewport focused".into();}let _=accent;});});});})}

fn draw_bottom_panel(ui:&mut egui::Ui,p:&mut EditorUiParams,page:BottomPage){design_system::card(ui,design_system::Surface::Container,|ui|{ui.horizontal(|ui|{for(candidate,label)in[(BottomPage::Console,"Console"),(BottomPage::Profiler,"Profiler"),(BottomPage::Output,"Output"),(BottomPage::Diagnostics,"Diagnostics")]{if ui.selectable_label(page==candidate,label).clicked(){p.workspace.layout.bottom_page=candidate;}}});design_system::separator(ui);match page{BottomPage::Console=>{design_system::console_info(ui,"editor workspace online");design_system::console_info(ui,&format!("commands {}",p.registry.iter().count()));design_system::console_info(ui,&format!("plugins {}",p.plugins.iter().count()));design_system::console_info(ui,&format!("selection {}",p.selection.entities.len()));},BottomPage::Profiler=>{ui.horizontal(|ui|{design_system::metric(ui,"FPS",&format!("{:.1}",p.profiler.fps),design_system::Emphasis::Success);design_system::metric(ui,"Frame",&format!("{:.2} ms",p.profiler.frame_time_ms),design_system::Emphasis::Info);design_system::metric(ui,"Samples",&p.profiler.samples.to_string(),design_system::Emphasis::Secondary);});},BottomPage::Output=>{design_system::body(ui,"Build output is emitted by the command executor.");if design_system::build(ui){p.command_bus.emit(crate::EditorCommandId("project.export"));}},BottomPage::Diagnostics=>{design_system::body(ui,&format!("Entities: {}",p.names.iter().count()));design_system::body(ui,&format!("Assets: {}",p.assets.entries.len()));}}});}
