//! Editor UI orchestration and workspace state.
use bevy::ecs::system::{ParamSet, SystemParam};
use bevy::prelude::*;
use bevy_egui::{egui, EguiContexts};
use crate::{assets::AssetDatabase,command::{EditorCommandBus,EditorCommandRegistry},docking::{show_dock_area,DockViewer,EditorDockState,TransformEdit},editor::EditorUiState,history::TransformHistory,project::{EditorMode,ProjectState},scene_model::EditorParent,selection::SelectionState,settings::EditorSettingsState,viewport::EditorEntity};
pub mod actions; pub mod assets; pub mod command_palette; pub mod design_system; pub mod layout; pub mod persistence; pub mod settings; pub mod theme; pub mod welcome; pub mod workspace;
use actions::{apply_entity_actions,UiActions};
use layout::LayoutState;
use welcome::{show_welcome,WelcomeState};

#[derive(Resource,Debug,Clone)]
pub struct WorkspaceUiState{pub layout:LayoutState,pub hierarchy_filter:String,pub asset_filter:String,pub toast:Option<String>,pub toast_seconds:f32}
impl Default for WorkspaceUiState{fn default()->Self{Self{layout:LayoutState::default(),hierarchy_filter:String::new(),asset_filter:String::new(),toast:None,toast_seconds:0.0}}}
impl WorkspaceUiState{pub fn toast(&mut self,text:impl Into<String>){self.toast=Some(text.into());self.toast_seconds=3.0}pub fn tick(&mut self,dt:f32){if self.toast_seconds>0.0{self.toast_seconds=(self.toast_seconds-dt).max(0.0);if self.toast_seconds==0.0{self.toast=None}}}}

#[derive(SystemParam)]
pub struct EditorUiParams<'w,'s>{pub contexts:EguiContexts<'w,'s>,pub workspace:ResMut<'w,WorkspaceUiState>,pub dock:ResMut<'w,EditorDockState>,pub state:ResMut<'w,EditorUiState>,pub settings:ResMut<'w,EditorSettingsState>,pub welcome:ResMut<'w,WelcomeState>,pub project:ResMut<'w,ProjectState>,pub selection:ResMut<'w,SelectionState>,pub registry:Res<'w,EditorCommandRegistry>,pub command_bus:ResMut<'w,EditorCommandBus>,pub plugins:Res<'w,crate::editor::EditorPluginRegistry>,pub assets:ResMut<'w,AssetDatabase>,pub profiler:Res<'w,crate::EditorProfiler>,pub history:ResMut<'w,TransformHistory>,pub transforms:Query<'w,'s,&'static Transform,With<EditorEntity>>,pub names:Query<'w,'s,(Entity,Option<&'static Name>),With<EditorEntity>>,pub visibility:Query<'w,'s,&'static Visibility,With<EditorEntity>>,pub parents:ParamSet<'w,'s,(Query<'w,'s,Option<&'static EditorParent>,With<EditorEntity>>,Query<'w,'s,&'static mut EditorParent,With<EditorEntity>>)>,pub commands:Commands<'w,'s>}

pub fn install_editor_ui(app:&mut App){app.init_resource::<WelcomeState>().init_resource::<WorkspaceUiState>().add_systems(bevy_egui::EguiPrimaryContextPass,editor_ui_system).add_systems(Update,ui_tick_system)}
fn ui_tick_system(time:Res<Time>,mut state:ResMut<WorkspaceUiState>){state.tick(time.delta_secs())}

fn editor_ui_system(mut p:EditorUiParams)->Result{
    let ctx=p.contexts.ctx_mut()?.clone();
    theme::apply_material_theme(&ctx);
    let settings_snapshot=p.settings.settings.clone();theme::apply_material_settings(&ctx,&settings_snapshot);
    if p.welcome.visible{return draw_welcome(&ctx,&mut p);}
    let entities=snapshot_entities(&p.names,&p.workspace.hierarchy_filter);let parents=snapshot_parents(&mut p,&entities);let selected_transform=snapshot_transform(&p);let selected_name=snapshot_name(&p);let selected_visible=snapshot_visible(&p);let plugins=snapshot_plugins(&p);
    let project_name=p.project.name.clone();let dirty=p.project.dirty;let mode=p.project.mode;let status=p.state.status.clone();let rect=ctx.viewport_rect();let mut top_commands:Vec<&'static str>=Vec::new();let mut nav_status=None;let mut actions=UiActions::default();
    egui::Area::new(egui::Id::new("bevy_gui_root")).order(egui::Order::Background).fixed_pos(rect.min).show(&ctx,|ui|{ui.set_min_size(rect.size());draw_top_bar(ui,&project_name,dirty,mode,&status,&mut top_commands);ui.add_space(6.0);ui.horizontal(|ui|{draw_nav(ui,&mut nav_status);ui.separator();ui.allocate_ui(ui.available_size(),|ui|{let mut viewer=make_viewer(&mut p.project,&mut p.selection,&mut p.state,&mut p.settings,&p.profiler,&mut p.assets,&entities,&parents,selected_transform,selected_name.clone(),selected_visible,&plugins,p.registry.iter().count());show_dock_area(ui,&mut p.dock,&mut viewer);actions=UiActions::from(&viewer);});});if let Some(message)=p.workspace.toast.as_deref(){ui.add_space(6.0);crate::ui::design_system::overlay(ui,|ui|{ui.label(message);});}});
    for id in top_commands{p.command_bus.emit(crate::EditorCommandId(id));}if let Some(status)=nav_status{p.state.status=status;}apply_actions(&mut p,&actions);Ok(())
}
fn draw_welcome(ctx:&egui::Context,p:&mut EditorUiParams)->Result{let result=egui::Area::new(egui::Id::new("bevy_gui_welcome")).order(egui::Order::Background).fixed_pos(ctx.viewport_rect().min).show(ctx,|ui|{ui.set_min_size(ctx.viewport_rect().size());show_welcome(ui,&mut p.welcome,&mut p.project,&mut p.state,&mut p.command_bus);});let _=result;Ok(())}
fn draw_top_bar(ui:&mut egui::Ui,project:&str,dirty:bool,mode:EditorMode,status:&str,commands:&mut Vec<&'static str>){crate::ui::design_system::toolbar(ui,|ui|{ui.horizontal(|ui|{ui.label(egui::RichText::new("✦ Bevy-GUI").size(17.0).strong());ui.separator();ui.label(project);crate::ui::design_system::dirty_badge(ui,dirty);ui.separator();if crate::ui::design_system::save(ui,dirty){commands.push("project.save");}if crate::ui::design_system::build(ui){commands.push("project.export");}if crate::ui::design_system::refresh(ui){commands.push("assets.refresh");}ui.separator();if crate::ui::design_system::play(ui,mode==EditorMode::Play){commands.push("project.play");}if crate::ui::design_system::pause(ui,mode==EditorMode::Paused){commands.push("project.pause");}if crate::ui::design_system::stop(ui){commands.push("project.stop");}ui.with_layout(egui::Layout::right_to_left(egui::Align::Center),|ui|{crate::ui::design_system::status(ui,status,match mode{EditorMode::Edit=>crate::ui::design_system::Emphasis::Info,EditorMode::Play=>crate::ui::design_system::Emphasis::Success,EditorMode::Paused=>crate::ui::design_system::Emphasis::Warning});});});})}
fn draw_nav(ui:&mut egui::Ui,status:&mut Option<String>){crate::ui::design_system::card(ui,crate::ui::design_system::Surface::Container,|ui|{ui.vertical(|ui|{ui.label(egui::RichText::new("NAV").strong());for(icon,label)in[("⌂","Home"),("▣","Scene"),("◫","Assets"),("⚙","Settings"),("▤","Console"),("◌","Profiler")]{if crate::ui::design_system::nav_button(ui,icon,label,label=="Scene").clicked(){*status=Some(label.to_owned());}}});})}
fn snapshot_entities(q:&Query<(Entity,Option<&Name>),With<EditorEntity>>,filter:&str)->Vec<(Entity,String)>{let f=filter.to_ascii_lowercase();q.iter().filter_map(|(e,n)|{let name=n.map(|x|x.as_str().to_owned()).unwrap_or_else(||format!("Entity {:?}",e));if f.is_empty()||name.to_ascii_lowercase().contains(&f){Some((e,name))}else{None}}).collect()}
fn snapshot_parents(p:&mut EditorUiParams,entities:&[(Entity,String)])->Vec<(Entity,Option<Entity>)>{let q=p.parents.p0();entities.iter().map(|(e,_)|(*e,q.get(*e).ok().flatten().and_then(|v|v.0))).collect()}
fn snapshot_transform(p:&EditorUiParams)->Option<TransformEdit>{let entity=p.selection.primary()?;let transform=*p.transforms.get(entity).ok()?;let(x,y,z)=transform.rotation.to_euler(EulerRot::XYZ);Some(TransformEdit{entity,translation:transform.translation,rotation:Vec3::new(x.to_degrees(),y.to_degrees(),z.to_degrees()),scale:transform.scale})}
fn snapshot_name(p:&EditorUiParams)->Option<String>{p.selection.primary().and_then(|e|p.names.get(e).ok()).and_then(|(_,n)|n.map(|v|v.as_str().to_owned()))}
fn snapshot_visible(p:&EditorUiParams)->Option<bool>{p.selection.primary().and_then(|e|p.visibility.get(e).ok()).map(|v|!matches!(*v,Visibility::Hidden))}
fn snapshot_plugins(p:&EditorUiParams)->Vec<String>{p.plugins.iter().map(|(name,version)|format!("{name} v{version}")).collect()}
fn make_viewer<'a>(project:&'a mut ProjectState,selection:&'a mut SelectionState,ui_state:&'a mut EditorUiState,settings:&'a mut EditorSettingsState,profiler:&'a crate::EditorProfiler,assets:&'a mut AssetDatabase,entities:&'a[(Entity,String)],parents:&'a[(Entity,Option<Entity>)],transform:Option<TransformEdit>,name:Option<String>,visible:Option<bool>,plugins:&'a[String],command_count:usize)->DockViewer<'a>{DockViewer{project,selection,ui_state,settings,profiler,assets,entities,parents,selected_transform:transform,selected_name:name,selected_visible:visible,plugin_names:plugins,command_count,transform_edit:None,name_edit:None,visibility_edit:None,viewport_focused:false,create_entity:false,delete_entity:None,duplicate_entity:None,save_requested:false,parent_selected:false,unparent_selected:false}}
fn apply_actions(p:&mut EditorUiParams,actions:&UiActions){let mut parents=p.parents.p1();apply_entity_actions(actions,&mut p.commands,&mut p.selection,&mut p.project,&mut p.history,&p.transforms,&mut parents);drop(parents);}
