use bevy::prelude::*;
use bevy_egui::egui;
use crate::{editor::{EditorPlugin,EditorPluginRegistry},panel::PanelRegistry,scene::{EditorPrimitive,EditorVisual,SceneBody,ScenePrimitive},scene_model::EditorParent,selection::SelectionState,viewport::EditorEntity};

pub struct InspectorEditorPlugin;
impl Default for InspectorEditorPlugin{fn default()->Self{Self}}
impl EditorPlugin for InspectorEditorPlugin{fn name(&self)->&'static str{"inspector"}fn build(&self,app:&mut App){app.world_mut().resource_mut::<EditorPluginRegistry>().register(self.name(),"2.2");app.world_mut().resource_mut::<PanelRegistry>().register(crate::panel::PanelId("inspector"),"Inspector",inspector_panel);}}

fn inspector_panel(world:&mut World,ui:&mut egui::Ui){let entity=world.get_resource::<SelectionState>().and_then(|selection|selection.primary());let Some(entity)=entity else{empty_inspector(ui);return};if world.get::<EditorEntity>(entity).is_none(){ui.colored_label(egui::Color32::RED,"Selected entity is not an editor entity.");return}
let snapshot={let mut query=world.query_filtered::<(Option<&Name>,Option<&Transform>,Option<&Visibility>,Option<&EditorParent>,Option<&EditorPrimitive>,Option<&EditorVisual>),With<EditorEntity>>();let Ok((name,transform,visibility,parent,primitive,visual))=query.get(world,entity)else{ui.colored_label(egui::Color32::RED,"Selected entity is no longer alive.");return};(name.map(Name::as_str).unwrap_or("Entity").to_owned(),transform.copied(),visibility.copied().map(|v|!matches!(v,Visibility::Hidden)).unwrap_or(true),parent.and_then(|v|v.0),primitive.copied().unwrap_or(EditorPrimitive(ScenePrimitive::None)),visual.map(|v|v.0.clone()))};
let(mut name_text,original_transform,mut visible,parent_entity,mut primitive,mut visual)=snapshot;let mut translation=original_transform.map(|v|v.translation).unwrap_or(Vec3::ZERO);let mut rotation=original_transform.map(|v|{let(x,y,z)=v.rotation.to_euler(EulerRot::XYZ);Vec3::new(x.to_degrees(),y.to_degrees(),z.to_degrees())}).unwrap_or(Vec3::ZERO);let mut scale=original_transform.map(|v|v.scale).unwrap_or(Vec3::ONE);
ui.horizontal(|ui|{ui.strong("Inspector");ui.weak(format!("Entity {:?}",entity));});ui.separator();
egui::CollapsingHeader::new("Identity").default_open(true).show(ui,|ui|{ui.horizontal(|ui|{ui.label("Name");if ui.text_edit_singleline(&mut name_text).changed(){world.entity_mut(entity).insert(Name::new(name_text.clone()));mark_dirty(world)}});ui.horizontal(|ui|{ui.label("Parent");ui.monospace(parent_entity.map(|v|format!("{:?}",v)).unwrap_or_else(||"<root>".into()));});});
egui::CollapsingHeader::new("Visibility").default_open(true).show(ui,|ui|{if ui.checkbox(&mut visible,"Visible in scene").changed(){world.entity_mut(entity).insert(if visible{Visibility::Inherited}else{Visibility::Hidden});mark_dirty(world)}});
let mut transform_changed=false;egui::CollapsingHeader::new("Transform").default_open(true).show(ui,|ui|{ui.label("Position");for(value,prefix)in[(&mut translation.x,"X "),(&mut translation.y,"Y "),(&mut translation.z,"Z ")]{transform_changed|=ui.add(egui::DragValue::new(value).prefix(prefix).speed(0.05)).changed()}ui.label("Rotation (degrees)");for(value,prefix)in[(&mut rotation.x,"X "),(&mut rotation.y,"Y "),(&mut rotation.z,"Z ")]{transform_changed|=ui.add(egui::DragValue::new(value).prefix(prefix).speed(0.5)).changed()}ui.label("Scale");for(value,prefix)in[(&mut scale.x,"X "),(&mut scale.y,"Y "),(&mut scale.z,"Z ")]{transform_changed|=ui.add(egui::DragValue::new(value).prefix(prefix).speed(0.02)).changed()}ui.horizontal(|ui|{if ui.button("Reset Position").clicked(){translation=Vec3::ZERO;transform_changed=true}if ui.button("Reset Rotation").clicked(){rotation=Vec3::ZERO;transform_changed=true}if ui.button("Reset Scale").clicked(){scale=Vec3::ONE;transform_changed=true}})});if transform_changed{if let Some(mut transform)=world.get_mut::<Transform>(entity){transform.translation=translation;transform.rotation=Quat::from_euler(EulerRot::XYZ,rotation.x.to_radians(),rotation.y.to_radians(),rotation.z.to_radians());transform.scale=scale}mark_dirty(world)}

egui::CollapsingHeader::new("Rendering").default_open(true).show(ui,|ui|{egui::ComboBox::from_label("Primitive").selected_text(format!("{:?}",primitive.0)).show_ui(ui,|ui|{for item in [ScenePrimitive::None,ScenePrimitive::Cube,ScenePrimitive::Plane,ScenePrimitive::Sphere,ScenePrimitive::Capsule]{if ui.selectable_value(&mut primitive.0,item,format!("{:?}",item)).changed(){world.entity_mut(entity).insert(primitive);if let Some(current)=visual.as_mut(){current.primitive=primitive.0;world.entity_mut(entity).insert(EditorVisual(current.clone()))}mark_dirty(world)}}});if visual.is_none(){visual=Some(crate::scene::SceneVisual::default())}let current=visual.as_mut().expect("visual initialized");let mut changed=false;changed|=ui.add(egui::Slider::new(&mut current.metallic,0.0..=1.0).text("Metallic")).changed();changed|=ui.add(egui::Slider::new(&mut current.roughness,0.0..=1.0).text("Roughness")).changed();let mut rgba=current.base_color;if ui.color_edit_button_rgba_unmultiplied(&mut rgba).changed(){current.base_color=rgba;changed=true}current.primitive=primitive.0;ui.label(format!("Mesh asset: {}",current.mesh_asset.as_deref().unwrap_or("<primitive>")));if changed{world.entity_mut(entity).insert(EditorVisual(current.clone()));mark_dirty(world)}});

egui::CollapsingHeader::new("Physics").default_open(true).show(ui,|ui|{let current=visual.get_or_insert_with(Default::default);let mut body=current.body;egui::ComboBox::from_label("Body").selected_text(format!("{:?}",body)).show_ui(ui,|ui|{for item in [SceneBody::None,SceneBody::Static,SceneBody::Dynamic,SceneBody::Kinematic]{if ui.selectable_value(&mut body,item,format!("{:?}",item)).changed(){current.body=body;world.entity_mut(entity).insert(EditorVisual(current.clone()));mark_dirty(world)}}});if ui.checkbox(&mut current.collision,"Collision enabled").changed(){world.entity_mut(entity).insert(EditorVisual(current.clone()));mark_dirty(world)}ui.small("Primitive colliders are generated by the runtime from saved physics metadata.");});

egui::CollapsingHeader::new("Audio").default_open(false).show(ui,|ui|{let current=visual.get_or_insert_with(Default::default);let mut changed=false;let mut path=current.audio.asset.clone().unwrap_or_default();ui.horizontal(|ui|{ui.label("Asset");if ui.text_edit_singleline(&mut path).changed(){current.audio.asset=if path.trim().is_empty(){None}else{Some(path.clone())};changed=true}});changed|=ui.checkbox(&mut current.audio.looping,"Loop").changed();changed|=ui.add(egui::Slider::new(&mut current.audio.volume,0.0..=2.0).text("Volume")).changed();changed|=ui.checkbox(&mut current.audio.spatial,"Spatial").changed();if changed{world.entity_mut(entity).insert(EditorVisual(current.clone()));mark_dirty(world)}ui.small("Audio assets are loaded from the project assets directory.");});

egui::CollapsingHeader::new("Components").default_open(true).show(ui,|ui|{component_status(ui,"EditorEntity",true);component_status(ui,"Name",world.get::<Name>(entity).is_some());component_status(ui,"Transform",world.get::<Transform>(entity).is_some());component_status(ui,"Visibility",world.get::<Visibility>(entity).is_some());component_status(ui,"EditorParent",world.get::<EditorParent>(entity).is_some());component_status(ui,"EditorPrimitive",world.get::<EditorPrimitive>(entity).is_some());component_status(ui,"EditorVisual",world.get::<EditorVisual>(entity).is_some())});}
fn component_status(ui:&mut egui::Ui,label:&str,present:bool){ui.horizontal(|ui|{ui.label(if present{"✓"}else{"○"});ui.label(label);});}
fn empty_inspector(ui:&mut egui::Ui){ui.vertical_centered(|ui|{ui.add_space(48.0);ui.label(egui::RichText::new("Inspector").size(18.0).strong());ui.label("Select an entity from the Hierarchy or Viewport.");});}
fn mark_dirty(world:&mut World){if let Some(mut project)=world.get_resource_mut::<crate::ProjectState>(){project.dirty=true}if let Some(mut scene)=world.get_resource_mut::<crate::scene_model::SceneEditorState>(){scene.mark_dirty()}}
