use bevy::prelude::*;
use std::collections::BTreeMap;

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum ComponentKind {
    Transform, Name, Visibility, Parent, Camera, Light, Mesh, Material, Physics, Collider, Animation, EditorPrimitive, EditorVisual, EditorEntity,
}
impl ComponentKind { pub fn display_name(self)->&'static str{match self{Self::Transform=>"Transform",Self::Name=>"Name",Self::Visibility=>"Visibility",Self::Parent=>"Parent",Self::Camera=>"Camera",Self::Light=>"Light",Self::Mesh=>"Mesh",Self::Material=>"Material",Self::Physics=>"Physics",Self::Collider=>"Collider",Self::Animation=>"Animation",Self::EditorPrimitive=>"Editor Primitive",Self::EditorVisual=>"Editor Visual",Self::EditorEntity=>"Editor Entity"}} pub fn category(self)->&'static str{match self{Self::Transform|Self::Name|Self::Visibility|Self::Parent=>"Core",Self::Camera|Self::Light|Self::Mesh|Self::Material=>"Rendering",Self::Physics|Self::Collider=>"Physics",Self::Animation=>"Animation",Self::EditorPrimitive|Self::EditorVisual|Self::EditorEntity=>"Editor"}}}
#[derive(Debug,Clone,Copy,PartialEq,Eq)]pub enum PropertyKind{Text,Bool,Float,Vec3,Color,Enum,ReadOnly}
#[derive(Debug,Clone)]pub struct PropertyDescriptor{pub name:&'static str,pub label:&'static str,pub kind:PropertyKind,pub editable:bool,pub tooltip:&'static str}
#[derive(Debug,Clone)]pub struct ComponentDescriptor{pub kind:ComponentKind,pub label:&'static str,pub category:&'static str,pub properties:&'static[PropertyDescriptor],pub removable:bool,pub addable:bool}
const TRANSFORM_PROPERTIES:&[PropertyDescriptor]=&[PropertyDescriptor{name:"translation",label:"Position",kind:PropertyKind::Vec3,editable:true,tooltip:"Local translation."},PropertyDescriptor{name:"rotation",label:"Rotation",kind:PropertyKind::Vec3,editable:true,tooltip:"Euler rotation in degrees."},PropertyDescriptor{name:"scale",label:"Scale",kind:PropertyKind::Vec3,editable:true,tooltip:"Local scale."}];
const NAME_PROPERTIES:&[PropertyDescriptor]=&[PropertyDescriptor{name:"value",label:"Name",kind:PropertyKind::Text,editable:true,tooltip:"Hierarchy display name."}];
const VISIBILITY_PROPERTIES:&[PropertyDescriptor]=&[PropertyDescriptor{name:"visible",label:"Visible",kind:PropertyKind::Bool,editable:true,tooltip:"Editor/runtime visibility."}];
const PARENT_PROPERTIES:&[PropertyDescriptor]=&[PropertyDescriptor{name:"parent",label:"Parent",kind:PropertyKind::ReadOnly,editable:false,tooltip:"Hierarchy parent."}];
const RENDER_PROPERTIES:&[PropertyDescriptor]=&[PropertyDescriptor{name:"asset",label:"Asset",kind:PropertyKind::Text,editable:true,tooltip:"Mesh or material asset reference."}];
const PHYSICS_PROPERTIES:&[PropertyDescriptor]=&[PropertyDescriptor{name:"body",label:"Body",kind:PropertyKind::Enum,editable:true,tooltip:"Physics body mode."},PropertyDescriptor{name:"collision",label:"Collision",kind:PropertyKind::Bool,editable:true,tooltip:"Generate a collider."}];
const ANIMATION_PROPERTIES:&[PropertyDescriptor]=&[PropertyDescriptor{name:"clip",label:"Clip",kind:PropertyKind::Text,editable:true,tooltip:"Active animation clip."},PropertyDescriptor{name:"speed",label:"Speed",kind:PropertyKind::Float,editable:true,tooltip:"Playback speed."}];
const EMPTY:&[PropertyDescriptor]=&[];
const DESCRIPTORS:&[ComponentDescriptor]=&[
 ComponentDescriptor{kind:ComponentKind::Transform,label:"Transform",category:"Core",properties:TRANSFORM_PROPERTIES,removable:false,addable:true},
 ComponentDescriptor{kind:ComponentKind::Name,label:"Name",category:"Core",properties:NAME_PROPERTIES,removable:false,addable:true},
 ComponentDescriptor{kind:ComponentKind::Visibility,label:"Visibility",category:"Core",properties:VISIBILITY_PROPERTIES,removable:true,addable:true},
 ComponentDescriptor{kind:ComponentKind::Parent,label:"Parent",category:"Core",properties:PARENT_PROPERTIES,removable:true,addable:true},
 ComponentDescriptor{kind:ComponentKind::Camera,label:"Camera",category:"Rendering",properties:EMPTY,removable:true,addable:true},
 ComponentDescriptor{kind:ComponentKind::Light,label:"Light",category:"Rendering",properties:EMPTY,removable:true,addable:true},
 ComponentDescriptor{kind:ComponentKind::Mesh,label:"Mesh",category:"Rendering",properties:RENDER_PROPERTIES,removable:true,addable:true},
 ComponentDescriptor{kind:ComponentKind::Material,label:"Material",category:"Rendering",properties:RENDER_PROPERTIES,removable:true,addable:true},
 ComponentDescriptor{kind:ComponentKind::Physics,label:"Physics",category:"Physics",properties:PHYSICS_PROPERTIES,removable:true,addable:true},
 ComponentDescriptor{kind:ComponentKind::Collider,label:"Collider",category:"Physics",properties:EMPTY,removable:true,addable:true},
 ComponentDescriptor{kind:ComponentKind::Animation,label:"Animation",category:"Animation",properties:ANIMATION_PROPERTIES,removable:true,addable:true},
 ComponentDescriptor{kind:ComponentKind::EditorPrimitive,label:"Editor Primitive",category:"Editor",properties:EMPTY,removable:false,addable:false},
 ComponentDescriptor{kind:ComponentKind::EditorVisual,label:"Editor Visual",category:"Editor",properties:EMPTY,removable:false,addable:false},
 ComponentDescriptor{kind:ComponentKind::EditorEntity,label:"Editor Entity",category:"Editor",properties:EMPTY,removable:false,addable:false},
];
#[derive(Resource,Debug,Clone)]pub struct ComponentRegistry{descriptors:BTreeMap<ComponentKind,ComponentDescriptor>}
impl Default for ComponentRegistry{fn default()->Self{let mut descriptors=BTreeMap::new();for descriptor in DESCRIPTORS{descriptors.insert(descriptor.kind,descriptor.clone());}Self{descriptors}}}
impl ComponentRegistry{pub fn descriptor(&self,kind:ComponentKind)->Option<&ComponentDescriptor>{self.descriptors.get(&kind)}pub fn iter(&self)->impl Iterator<Item=&ComponentDescriptor>{self.descriptors.values()}pub fn by_category(&self,category:&str)->impl Iterator<Item=&ComponentDescriptor>{self.descriptors.values().filter(move|item|item.category==category)}pub fn detect_entity(&self,world:&World,entity:Entity)->Vec<ComponentKind>{let mut result=Vec::new();if world.get::<Transform>(entity).is_some(){result.push(ComponentKind::Transform)}if world.get::<Name>(entity).is_some(){result.push(ComponentKind::Name)}if world.get::<Visibility>(entity).is_some(){result.push(ComponentKind::Visibility)}if world.get::<crate::EditorParent>(entity).is_some(){result.push(ComponentKind::Parent)}if world.get::<Camera>(entity).is_some(){result.push(ComponentKind::Camera)}if world.get::<DirectionalLight>(entity).is_some()||world.get::<PointLight>(entity).is_some()||world.get::<SpotLight>(entity).is_some(){result.push(ComponentKind::Light)}if world.get::<Mesh3d>(entity).is_some(){result.push(ComponentKind::Mesh)}if world.get::<MeshMaterial3d<StandardMaterial>>(entity).is_some(){result.push(ComponentKind::Material)}if world.get::<avian3d::prelude::RigidBody>(entity).is_some(){result.push(ComponentKind::Physics)}if world.get::<avian3d::prelude::Collider>(entity).is_some(){result.push(ComponentKind::Collider)}if world.get::<crate::AnimationLibrary>(entity).is_some()||world.get::<crate::AnimatorState>(entity).is_some(){result.push(ComponentKind::Animation)}if world.get::<crate::EditorPrimitive>(entity).is_some(){result.push(ComponentKind::EditorPrimitive)}if world.get::<crate::scene::EditorVisual>(entity).is_some(){result.push(ComponentKind::EditorVisual)}if world.get::<crate::viewport::EditorEntity>(entity).is_some(){result.push(ComponentKind::EditorEntity)}result}pub fn validate(&self)->Result<(),Vec<String>>{let mut errors=Vec::new();for descriptor in self.descriptors.values(){if descriptor.label.is_empty(){errors.push(format!("component {:?} has empty label",descriptor.kind))}for property in descriptor.properties{if property.name.is_empty()||property.label.is_empty(){errors.push(format!("component {:?} has invalid property",descriptor.kind))}if property.editable&&matches!(property.kind,PropertyKind::ReadOnly){errors.push(format!("property {} is editable but read-only",property.name))}}}if errors.is_empty(){Ok(())}else{Err(errors)}}pub fn component_count(&self)->usize{self.descriptors.len()}pub fn property_count(&self)->usize{self.descriptors.values().map(|d|d.properties.len()).sum()}}
pub fn install_component_registry(app:&mut App){app.init_resource::<ComponentRegistry>();}
#[cfg(test)]mod tests{use super::*;#[test]fn registry_contains_engine_components(){let registry=ComponentRegistry::default();assert!(registry.descriptor(ComponentKind::Physics).is_some());assert!(registry.descriptor(ComponentKind::Animation).is_some());assert!(registry.component_count()>=14);assert!(registry.validate().is_ok());}}
