//! Bevy-GUI: a plugin-first editor and game-engine platform built on Bevy 0.19.
//! The editor, authored scene format, runtime bootstrap, diagnostics, physics,
//! input and engine services share one reusable Rust architecture.

pub mod app;
pub mod asset_pipeline;
pub mod assets;
pub mod command;
pub mod command_executor;
pub mod component_registry;
pub mod docking;
pub mod editor;
pub mod engine;
pub mod engine_features;
pub mod engine_runtime;
pub mod export;
pub mod game;
pub mod history;
pub mod input;
pub mod jackdaw_ui;
pub mod panel;
pub mod plugins;
pub mod prefab;
pub mod profiler;
pub mod project;
pub mod runtime;
pub mod scene;
pub mod scene_model;
pub mod scene_tools;
pub mod selection;
pub mod settings;
pub mod ui;
pub mod viewport;
pub mod viewport2d;

pub use app::BevyGuiPlugin;
pub use asset_pipeline::{ImportDatabase, ImportedAsset, ImportKind, ImportReport, ImportSettings, ImportStatus};
pub use assets::{AssetDatabase, AssetEntry, AssetKind};
pub use command::{EditorCommand, EditorCommandBus, EditorCommandId, EditorCommandRegistry};
pub use command_executor::CommandExecutionState;
pub use component_registry::{ComponentDescriptor, ComponentKind, ComponentRegistry, PropertyDescriptor, PropertyKind};
pub use docking::{EditorDockState, EditorTab};
pub use editor::{EditorPanel, EditorPanelContext, EditorPlugin, EditorPluginRegistry, ViewportMode};
pub use engine::{load_runtime_scene, project_engine_paths, EnginePaths, EnginePlugin, EngineRuntimeConfig, EngineRuntimePlugin, EngineSettings, RuntimeEntity};
pub use engine_features::{EngineDiagnostics, EngineEventMonitor, EngineEventRecord, EngineFeature, EngineFeatureRegistry, EngineFeaturesPlugin, EngineGraphRegistry, EngineSystemInfo};
pub use engine_runtime::{EngineClock, EngineFrameBudget, EngineFrameEvent, EngineRuntimeCorePlugin};
pub use game::{build_game_app, GameConfig};
pub use history::{TransformHistory, TransformSnapshot};
pub use input::{EngineAction, EngineActionEvent, EngineInputMap, EngineInputPlugin};
pub use jackdaw_ui::JackdawUiPlugin;
pub use panel::{PanelId, PanelRegistry};
pub use prefab::{load_prefab, prefab_path, save_prefab, spawn_prefab, PrefabDocument, PrefabInstanceOptions, PrefabIoError, PrefabNode};
pub use profiler::EditorProfiler;
pub use project::{create_project, load_project, project_file, save_project, EditorMode, ProjectIoError, ProjectManifest, ProjectState};
pub use runtime::PlaySession;
pub use scene::{load_scene, load_scene as load_authored_scene, save_scene, spawn_scene, spawn_scene_with_renderables, EditorPrimitive, SceneDocument, SceneEntity, SceneIoError, SceneNode, ScenePrimitive, SceneVisual};
pub use scene_model::{EditorParent, SceneEditorState, SceneNodeModel};
pub use scene_tools::{delete_subtree, duplicate_subtree, reparent_entity, validate_scene, SceneSelectionSet, SceneTool, SceneValidationReport};
pub use selection::SelectionState;
pub use settings::{load_settings, save_settings, EditorSettings, EditorSettingsState};
pub use viewport::EditorEntity;
