use bevy::prelude::*;
use std::collections::{BTreeMap,BTreeSet};
use crate::{scene::SceneDocument,SceneEntity};

#[derive(Debug,Clone,Copy,PartialEq,Eq)]pub enum SceneTool{Select,Move,Rotate,Scale,Pan,Create,Erase}
impl Default for SceneTool{fn default()->Self{Self::Select}}
#[derive(Debug,Clone,Copy,PartialEq,Eq)]pub enum SelectionMode{Replace,Add,Toggle,Subtract}
impl Default for SelectionMode{fn default()->Self{Self::Replace}}
#[derive(Debug,Clone)]pub struct SceneValidationIssue{pub severity:ValidationSeverity,pub entity_id:Option<u64>,pub message:String}
#[derive(Debug,Clone,Copy,PartialEq,Eq)]pub enum ValidationSeverity{Error,Warning,Info}
#[derive(Debug,Clone,Default)]pub struct SceneValidationReport{pub issues:Vec<SceneValidationIssue>}
impl SceneValidationReport{pub fn errors(&self)->usize{self.issues.iter().filter(|i|i.severity==ValidationSeverity::Error).count()}pub fn warnings(&self)->usize{self.issues.iter().filter(|i|i.severity==ValidationSeverity::Warning).count()}pub fn is_valid(&self)->bool{self.errors()==0}}
#[derive(Resource,Debug,Clone,Default)]pub struct SceneSelectionSet{pub selected:BTreeSet<u64>,pub focused:Option<u64>}
impl SceneSelectionSet{pub fn select(&mut self,id:u64,mode:SelectionMode){match mode{SelectionMode::Replace=>{self.selected.clear();self.selected.insert(id);self.focused=Some(id)},SelectionMode::Add=>{self.selected.insert(id);self.focused=Some(id)},SelectionMode::Toggle=>{if !self.selected.remove(&id){self.selected.insert(id);self.focused=Some(id)}else if self.focused==Some(id){self.focused=self.selected.iter().next().copied()}},SelectionMode::Subtract=>{self.selected.remove(&id);if self.focused==Some(id){self.focused=self.selected.iter().next().copied()}}}}pub fn clear(&mut self){self.selected.clear();self.focused=None}pub fn contains(&self,id:u64)->bool{self.selected.contains(&id)}pub fn len(&self)->usize{self.selected.len()}pub fn is_empty(&self)->bool{self.selected.is_empty()}}
pub fn validate_scene(document:&SceneDocument)->SceneValidationReport{let mut report=SceneValidationReport::default();let mut ids=BTreeSet::new();let by_id:BTreeMap<u64,&SceneEntity>=document.entities.iter().map(|e|(e.id,e)).collect();for entity in &document.entities{if !ids.insert(entity.id){report.issues.push(SceneValidationIssue{severity:ValidationSeverity::Error,entity_id:Some(entity.id),message:format!("duplicate entity id {}",entity.id)})}if entity.name.trim().is_empty(){report.issues.push(SceneValidationIssue{severity:ValidationSeverity::Warning,entity_id:Some(entity.id),message:"entity has an empty name".into()})}if !entity.translation.iter().all(|v|v.is_finite())||!entity.rotation.iter().all(|v|v.is_finite())||!entity.scale.iter().all(|v|v.is_finite()){report.issues.push(SceneValidationIssue{severity:ValidationSeverity::Error,entity_id:Some(entity.id),message:"entity contains a non-finite transform value".into()})}if let Some(parent)=entity.parent{if parent==entity.id{report.issues.push(SceneValidationIssue{severity:ValidationSeverity::Error,entity_id:Some(entity.id),message:"entity is its own parent".into()})}if !by_id.contains_key(&parent){report.issues.push(SceneValidationIssue{severity:ValidationSeverity::Error,entity_id:Some(entity.id),message:format!("missing parent {}",parent)})}}}for entity in &document.entities{let mut seen=BTreeSet::new();let mut current=entity.parent;while let Some(parent)=current{if !seen.insert(parent){report.issues.push(SceneValidationIssue{severity:ValidationSeverity::Error,entity_id:Some(entity.id),message:"parent hierarchy contains a cycle".into()});break}current=by_id.get(&parent).and_then(|node|node.parent)}}if document.entities.is_empty(){report.issues.push(SceneValidationIssue{severity:ValidationSeverity::Info,entity_id:None,message:"scene contains no entities".into()})}report}
pub fn collect_subtree(document:&SceneDocument,root_id:u64)->Vec<SceneEntity>{let mut result=Vec::new();let mut queue=vec![root_id];let mut visited=BTreeSet::new();while let Some(id)=queue.pop(){if !visited.insert(id){continue}let Some(node)=document.entities.iter().find(|e|e.id==id)else{continue};result.push(node.clone());for child in document.entities.iter().filter(|e|e.parent==Some(id)){queue.push(child.id)}}result.sort_by_key(|e|e.id);result}
pub fn clone_subtree(document:&SceneDocument,root_id:u64,id_start:u64,name_suffix:&str)->Option<Vec<SceneEntity>>{let original=collect_subtree(document,root_id);if original.is_empty(){return None}let mut mapping=BTreeMap::new();for(index,node)in original.iter().enumerate(){mapping.insert(node.id,id_start+index as u64);}let mut cloned=Vec::with_capacity(original.len());for node in original{cloned.push(SceneEntity{id:*mapping.get(&node.id).unwrap_or(&node.id),parent:node.parent.and_then(|p|mapping.get(&p).copied()),name:format!("{}{}",node.name,name_suffix),translation:node.translation,rotation:node.rotation,scale:node.scale,visible:node.visible})}Some(cloned)}
pub fn next_scene_id(document:&SceneDocument)->u64{document.entities.iter().map(|e|e.id).max().unwrap_or(0).saturating_add(1)}pub fn rename_entity(document:&mut SceneDocument,id:u64,name:impl Into<String>)->bool{let Some(entity)=document.entities.iter_mut().find(|e|e.id==id)else{return false};entity.name=name.into();true}
pub fn reparent_entity(document:&mut SceneDocument,child:u64,parent:Option<u64>)->Result<(),String>{if child==parent.unwrap_or(0){return Err("entity cannot be its own parent".into())}if !document.entities.iter().any(|e|e.id==child){return Err(format!("child entity {} does not exist",child))}if let Some(parent_id)=parent{if !document.entities.iter().any(|e|e.id==parent_id){return Err(format!("parent entity {} does not exist",parent_id))}let mut current=Some(parent_id);while let Some(id)=current{if id==child{return Err("reparenting would create a hierarchy cycle".into())}current=document.entities.iter().find(|e|e.id==id).and_then(|e|e.parent)}}document.entities.iter_mut().find(|e|e.id==child).unwrap().parent=parent;Ok(())}
pub fn delete_subtree(document:&mut SceneDocument,root_id:u64)->usize{let ids:BTreeSet<u64>=collect_subtree(document,root_id).into_iter().map(|e|e.id).collect();let before=document.entities.len();document.entities.retain(|e|!ids.contains(&e.id));before.saturating_sub(document.entities.len())}
pub fn duplicate_subtree(document:&mut SceneDocument,root_id:u64,suffix:&str)->Result<Vec<u64>,String>{let cloned=clone_subtree(document,root_id,next_scene_id(document),suffix).ok_or_else(||"root entity does not exist".to_owned())?;let ids=cloned.iter().map(|e|e.id).collect::<Vec<_>>();document.entities.extend(cloned);Ok(ids)}
